# Site settings
title: Cassidy Williams
email: cassidoo@gmail.com
author: Cassidy Williams
description: "Cassidy's attempts at writing things."
baseurl: ""
url: "http://cassidoo.github.io"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
